server:
  port: 9000

spring:
  application:
    name: authorization-server
  profiles:
    active: ${SPRING_PROFILE:default}
  ldap:
    embedded:
      port: 8389
      ldif: classpath:ldap/users.ldif
      base-dn: dc=springframework,dc=org

  datasource:
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

  flyway:
    default-schema: public
    schemas: public
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
    locations: classpath:${FLYWAY_LOCATION:/db/migration,/db/data} # ,/db/data

  security:
    oauth2:
      resourceserver:
        client: ${CLIENT}
        client-secret: ${CLIENT_SECRET}
        jwt:
          issuer-uri: ${ISSUER_URI}
      redirect-url: ${REDIRECT_URL}
      allowed-origins: ${ALLOWED_ORIGIN}
      allowed-headers: ${ALLOWED_HEADER}
      allowed-methods: ${ALLOWED_METHOD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

